config/routes.rb
Rails.application.routes.draw do

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  #get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  #get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  #resources :agreements do
  #  member do
  #    patch :validate
  #    patch :return_for_review
  #  end
  #end

  resources :agreements do
    resources :members, only: [:index, :new, :create, :destroy, :show, :edit]
    member do
      post :upload_document
      post :update_status
    end
    resources :agreement_logs, only: [:index, :create]
  end
  resources :documents, only: [:destroy]
  resources :clients
  resources :users

  #resources :agreements
  resources :agreement_types

  #root "agreements#index"

  root 'home#index'
  #root "sessions#new"

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')
  #get '/logout', to: 'sessions#destroy'
  #get '/login' => 'sessions#login'

  #get '/auth/:provider/callback' => 'sessions#create'
  #get '/auth/failure' => 'sessions#failure'
  #get '/logout' => 'sessions#destroy'

  get '/login', to: 'sessions#new', as: :login
  #delete '/logout', to: 'sessions#destroy', as: :logout
  get '/logout', to: 'sessions#destroy', as: :logout

  get '/dashboard', to: 'dashboard#index', as: :dashboard
  get 'dashboard/:id', to: 'dashboard#show', as: :dashboard_show

  namespace :api do
    post "proxy_x_oauth2", to: "proxy_mailer#re_send"
  end

end

app/controllers/dashboard_controller.rb
# app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.recent_hundred
  end

  def show
    @user = User.find(params[:id])
  end

end

app/views/dashboard/index.html.haml
%h1 Space
%h2.text-2xl.text-gray-700.m-0
  .table-container.relative.overflow-auto.max-h-96 Contratos
  %table#dashboard-table.min-w-full.border-collapse
    %thead.bg-gray-100.text-gray-700.sticky.top-0.uppercase.text-sm
      %tr
        %th.px-4.py-2.border-b.border-gray-300.text-left Clave
        %th.px-4.py-2.border-b.border-gray-300.text-left Nombre
        %th.px-4.py-2.border-b.border-gray-300.text-left Status
        %th.px-4.py-2.border-b.border-gray-300.text-left CURP
        %th.px-4.py-2.border-b.border-gray-300.text-left Email
        %th.px-4.py-2.border-b.border-gray-300.text-left Role

    %tbody
      - @users.each do |user|
        %tr.bg-white.odd:bg-gray-100.cursor-pointer{"data-controller" => "navigate", "data-action" => "click->navigate#toShow", "data-navigate-url" => dashboard_show_path(user)}
          %td.px-4.py-1.border-b.border-gray-200.text-sm= user.clave
          %td.px-4.py-1.border-b.border-gray-200.text-sm= user.nombre
          %td.px-4.py-1.border-b.border-gray-200.text-sm= user.status
          %td.px-4.py-1.border-b.border-gray-200.text-sm= user.curp
          %td.px-4.py-1.border-b.border-gray-200.text-sm= user.email
          %td.px-4.py-1.border-b.border-gray-200.text-sm= user.role

app/views/dashboard/show.html.haml
-# app/views/dashboard/show.html.haml

%div.mt-24.px-4
  %h2.text-2xl.font-semibold.text-gray-800.mt-4= @user.nombre
  %p.text-gray-600.mt-2
    %strong Clave:
    = @user.clave
  %p.text-gray-600.mt-2
    %strong Status:
    = @user.status
  %p.text-gray-600.mt-2
    %strong CURP:
    = @user.curp
  %p.text-gray-600.mt-2
    %strong Email:
    = @user.email
  %p.text-gray-600.mt-2
    %strong Role:
    = @user.role

  %div.mt-6
    = link_to "Back", dashboard_path(anchor: "dashboard-table"), data: { turbo: true }, class: "text-blue-500 hover:underline"