config/routes.rb
Rails.application.routes.draw do

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  #get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  #get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  #resources :agreements do
  #  member do
  #    patch :validate
  #    patch :return_for_review
  #  end
  #end

  resources :agreements do
    resources :members, only: [:index, :new, :create, :destroy, :show, :edit]
    member do
      post :upload_document
      post :update_status
    end
    resources :agreement_logs, only: [:index, :create]
  end
  resources :documents, only: [:destroy]
  resources :clients
  resources :users

  #resources :agreements
  resources :agreement_types

  #root "agreements#index"

  root 'home#index'
  #root "sessions#new"

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')
  #get '/logout', to: 'sessions#destroy'
  #get '/login' => 'sessions#login'

  #get '/auth/:provider/callback' => 'sessions#create'
  #get '/auth/failure' => 'sessions#failure'
  #get '/logout' => 'sessions#destroy'

  get '/login', to: 'sessions#new', as: :login
  #delete '/logout', to: 'sessions#destroy', as: :logout
  get '/logout', to: 'sessions#destroy', as: :logout

  get '/dashboard', to: 'dashboard#index', as: :dashboard
  get 'dashboard/:id', to: 'dashboard#show', as: :dashboard_show

  namespace :api do
    post "proxy_x_oauth2", to: "proxy_mailer#re_send"
  end

end

app/controllers/agreement_types_controller.rb
class AgreementTypesController < ApplicationController

  before_action :set_agreement_type, only: [:show, :edit, :update, :destroy]

  add_breadcrumb "Tipos", :agreement_types

  def index
    @agreement_types = AgreementType.all
  end

  def show
    add_breadcrumb @agreement_type.name, agreement_type_path(@agreement_type)
  end

  def edit
    add_breadcrumb @agreement_type.name, agreement_type_path(@agreement_type)
    add_breadcrumb "Edición", edit_agreement_type_path(@agreement_type)
  end

  def new
    @agreement_type = AgreementType.new

    add_breadcrumb "Nuevo", '#'

  end

  def create
    @agreement_type = AgreementType.new(agreement_type_params)
    if @agreement_type.save
      redirect_to agreement_types_path, notice: 'Agreement Type was successfully created.'
    else
      render :new
    end
  end

  def update
    if @agreement_type.update(agreement_type_params)
      redirect_to agreement_type_path(@agreement_type), notice: 'Agreement Type was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @agreement_type.destroy
    redirect_to agreement_types_path, notice: 'Agreement Type was successfully deleted.'
  end

  private

  def set_agreement_type
    @agreement_type = AgreementType.find(params[:id])
  end

  def agreement_type_params
    params.require(:agreement_type).permit(:name, :description, :required_documents, :requires_technical_responsible, :has_financial_terms)
  end

end

app/helpers/agreement_types_helper.rb
module AgreementTypesHelper
end

app/views/agreement_types/_form.html.haml
= form_with(model: @agreement_type, local: true) do |form|
  - if @agreement_type.errors.any?
    #error_explanation
      %h2= pluralize(@agreement_type.errors.count, "error") + " prohibited this agreement type from being saved:"
      %ul
        - @agreement_type.errors.full_messages.each do |message|
          %li= message

  .field
    = form.label "Nombre"
    = form.text_field :name

  .field
    = form.label "Descripción"
    = form.text_area :description

  .field
    = form.label "Documentos Requeridos"
    = form.text_area :required_documents

  .field
    = form.label "Requiere Responsable Técnico"
    = form.check_box :requires_technical_responsible

  .field
    = form.label "Incluye Términos Financieros"
    = form.check_box :has_financial_terms

  .actions
    = form.submit

app/views/agreement_types/edit.html.haml
%h1 Edit Agreement Type
= render 'form', agreement_type: @agreement_type
= link_to 'Back', agreement_types_path

app/views/agreement_types/index.html.haml
%h1 Agreement Types

= link_to 'New Agreement Type', new_agreement_type_path, class: "btn btn-primary"

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Actions
  %tbody
    - @agreement_types.each do |agreement_type|
      %tr
        %td= agreement_type.name
        %td= agreement_type.description
        %td
          = link_to 'Show', agreement_type_path(agreement_type)
          |
          = link_to 'Edit', edit_agreement_type_path(agreement_type)
          |
          = link_to 'Delete', agreement_type_path(agreement_type), method: :delete, data: { confirm: 'Are you sure?' }

app/views/agreement_types/new.html.haml
%h1 New Agreement Type
= render 'form', agreement_type: @agreement_type
= link_to 'Back', agreement_types_path

app/views/agreement_types/show.html.haml
%h1= @agreement_type.name
%p
  %strong Description:
  = @agreement_type.description
%p
  %strong Has Financial Terms:
  = @agreement_type.has_financial_terms ? "Yes" : "No"

= link_to 'Edit', edit_agreement_type_path(@agreement_type)
|
= link_to 'Back', agreement_types_path