config/routes.rb
Rails.application.routes.draw do

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  #get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  #get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  #resources :agreements do
  #  member do
  #    patch :validate
  #    patch :return_for_review
  #  end
  #end

  resources :agreements do
    resources :members, only: [:index, :new, :create, :destroy, :show, :edit]
    member do
      post :upload_document
      post :update_status
    end
    resources :agreement_logs, only: [:index, :create]
  end
  resources :documents, only: [:destroy]
  resources :clients
  resources :users

  #resources :agreements
  resources :agreement_types

  #root "agreements#index"

  root 'home#index'
  #root "sessions#new"

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')
  #get '/logout', to: 'sessions#destroy'
  #get '/login' => 'sessions#login'

  #get '/auth/:provider/callback' => 'sessions#create'
  #get '/auth/failure' => 'sessions#failure'
  #get '/logout' => 'sessions#destroy'

  get '/login', to: 'sessions#new', as: :login
  #delete '/logout', to: 'sessions#destroy', as: :logout
  get '/logout', to: 'sessions#destroy', as: :logout

  get '/dashboard', to: 'dashboard#index', as: :dashboard
  get 'dashboard/:id', to: 'dashboard#show', as: :dashboard_show

  namespace :api do
    post "proxy_x_oauth2", to: "proxy_mailer#re_send"
  end

end

app/models/agreement_type.rb
class AgreementType < ApplicationRecord

  has_many :agreements

  validates :name, presence: true

end

app/controllers/agreements_controller.rb
class AgreementsController < ApplicationController

  # Agregar breadcrumbs para las rutas principales
  add_breadcrumb "Convenios", :agreements

  before_action :set_agreement, only: [:show, :edit, :update, :validate, :return_for_review, :upload_document, :update_status]
  before_action :authenticate_user!
  before_action :set_breadcrumbs_for_edition, only: [:edit, :update]
  before_action :set_users_cyt_actives, only: [:new, :edit, :show]

  def index

    @agreements = Agreement.for_table(current_user).includes(:agreement_type).order('id': :desc)

    # Realiza una sola consulta a la base de datos externa para obtener los solicitantes
    # Esta consulta evita el problema del N+1
    #employees_ids = @agreements.map(&:creator_id).compact # sin nils
    employees_ids = @agreements.flat_map { |a| [a.creator_id, a.requester_id] }.compact
    # User usa el scope default que solo carga 5 atributos
    @employees_on_agreements = User.where(clave: employees_ids.map { |id| format('%05d', id) }).index_by(&:clave)

  end

  def show
    add_breadcrumb @agreement.title, agreement_path(@agreement)

    # @agreement = Agreement.find(params[:id])
    #Rails.logger.debug "Agreement en Show: #{@agreement.inspect} <<------------ 0"
    #Rails.logger.debug "Responsables Técnicos: #{@agreement.technical_responsibles.inspect} <------------ 1"

    # en el show siempre tengo uno listo por si agrega
    #@technical_responsible = @agreement.technical_responsibles.build

    # en show tengo un documento listo
    #@agreement.documents.build # Para añadir nuevos documentos desde el formulario
    @document = @agreement.documents.build
    #@document = Document.new

    # Show con acceso basado en Rules
    @can_edit_agreement = can_edit_agreement?
    @can_manage_technicals = can_manage_technicals?
    @can_manage_documents = can_manage_documents?

  end

  def upload_document
    #Rails.logger.debug "Parámetros completos: #{params.inspect} <----- "
    #Rails.logger.debug "Parametros recibidos >>>>>>>>: #{document_params.inspect} |||| #{params[:id]} <<<<<<<<<<< "

    #@agreement = Agreement.find(params[:id])
    @document = @agreement.documents.new(document_params)

    if @document.save
      flash[:notice] = "Documento subido correctamente."
      redirect_to agreement_path(@agreement, anchor: 'document-form')
    else
      # Prepara los datos necesarios para la vista `show`
      #@documents = @agreement.documents # Asegúrate de tener los documentos cargados
      #flash.now[:alert] = "Error al subir el documento."
      #render :show, status: :unprocessable_entity #  422 Unprocessable Entity, que indica que los datos no pasaron las validaciones. Esto es importante para mantener estándares RESTful.

      # Alternativa. Redirigir con msgs flash. Queda mas limpio. pero el @document se renueva
      # pierdo los datos pero evito lo confuso de /agreements/9/upload_document
      # flash[:alert] = @document.errors.full_messages.to_sentence
      flash[:alert_document] = @document.errors.full_messages.to_sentence
      redirect_to agreement_path(@agreement, anchor: 'alert-document')
    end
  end

  def validate
    @agreement.validado!
    AgreementMailer.agreement_validated(@agreement).deliver_later
    redirect_to agreements_path, notice: "El acuerdo ha sido validado."
  end

  def return_for_review
    @agreement.devuelto!
    AgreementMailer.agreement_returned(@agreement).deliver_later
    redirect_to agreements_path, notice: "El acuerdo ha sido devuelto con comentarios."
  end

  def new

    @agreement = Agreement.new(client_type: 'persona_moral',
                               signature_date: Date.today, start_date: Date.today, end_date: Date.today + 1.month,
                               amount: 0.00, status: "pendiente")

    @agreement.creator_id = current_user.id
    @agreement.requester_id = current_user.id

    add_breadcrumb "Nuevo", '#'

  end

  def create

    @agreement = Agreement.new(agreement_params)
    @agreement.creator_id = current_user.id

    if @agreement.save

      AgreementLog.create(
        agreement: @agreement,
        status: :pendiente,
        owner_id: current_user.id,
        message: "Se crea convenio/contrato",
        by_system: true
      )

      flash[:notice] = "El acuerdo se creó correctamente."
      redirect_to agreement_path(@agreement) # Redirige a la vista de detalle del acuerdo
    else
      add_breadcrumb "Nuevo", '#'
      flash[:alert] = @agreement.errors.full_messages
      render :new, status: :unprocessable_entity , anchor: "alert-agreement" # Renderiza la vista 'new' si hay errores
    end

  end

  def edit
    #add_breadcrumb @agreement.title, agreement_path(@agreement)
    #add_breadcrumb "Edición", edit_agreement_path(@agreement)
  end

  def update
    if @agreement.update(agreement_params)
      flash[:notice] = "Los cambios se guardaron correctamente."
      redirect_to @agreement
      # render :edit
      #redirect_to edit_agreement_path(@agreement, anchor: "btn-save-agreement"), notice:  "Los cambios se guardaron correctamente."
    else
      flash[:alert] = @agreement.errors.full_messages #.to_sentence
      render :edit
      # redirect_to edit_agreement_path(@agreement, anchor: "btn-save-agreement")
    end
  end

  def update_status_deprecated
    agreement = Agreement.find(params[:id])
    new_status = params[:status]

    if agreement.can_change_status?(current_user, new_status)
      agreement.update!(status: new_status)
      flash[:notice] = "El estado se actualizó correctamente."
    else
      flash[:alert] = "No tienes permisos para realizar esta acción."
    end
    redirect_to agreement
  end

  # Acción para cambiar el estado del acuerdo
  def update_status

    new_status = params[:new_status]

    # Verifica si el usuario tiene permiso para cambiar el estado
    if @agreement.allowed_status_changes(current_user).include?(new_status)
      old_status = @agreement.status
      @agreement.update!(status: new_status)
      # Registro del cambio en AgreementLog
      AgreementLog.create!(
        agreement: @agreement,
        status: new_status,
        owner_id: current_user.id,
        message: "Status cambiado de #{Agreement.status_info(old_status)[:human]} a #{Agreement.status_info(new_status)[:human]}",
        by_system: true
      )
      flash[:notice] = "El estado fue cambiado exitosamente a #{Agreement.status_info(status)[:human]}."
    else
      flash[:alert] = "No tienes permiso para cambiar el estado."
    end

    # Redirigir de vuelta al acuerdo
    redirect_to agreements_path
  rescue ActiveRecord::RecordInvalid
    flash[:alert] = "No se pudo cambiar el estado. Por favor, inténtalo de nuevo."
    redirect_to @agreement
  end

  private

   def set_agreement
    @agreement = Agreement.find(params[:id])
  end

  def agreement_params
    params.require(:agreement).permit(:title, :agreement_type_id, :creator_id, :requester_id, :client_name, :client_address,
      :client_type, :witness_name, :witness_position, :objective, :obligations, :benefits,
      :signature_date, :start_date, :end_date, :amount, :signed_by_client, :signed_by_requester, :signed_by_director,
                                      :status, :code, :notes)
  end

  def document_params
    params.require(:document).permit(:document_type_id, :file, :notes)
  end

  def set_breadcrumbs_for_edition
    add_breadcrumb @agreement.title, agreement_path(@agreement)
    add_breadcrumb "Edición", edit_agreement_path(@agreement)
  end

  <<-RULES
    En el Show de Agreement.

    Regla 1: Si el status esta en :pendiente, todos los controles estan habilitados sin importar el :profile del usuario.

    Regla 2: Si el status No esta en :pendiente, solamente los usuarios con profile de :juridico pueden hacer todos los cambios.

    Regla 3: la excepcion de la regla 2 es cuando el status esta en :aprobado y el usuario es el creator o tiene profile de :solicitante. 
    En este caso el usuario puede subir y borrar documentos.

    De acuerdo a las 3 reglas, los controles a deshabilitar (o habilitar) son el boton de edicion de agreement, 
    los botones de eliminar tecnico, no agregar el tr de la form_with de tecnicos, deshabilitar el boton de eliminar 
    documento, y no poner el tr del form_with de documentos.

  RULES

  # Regla 1 y 2
  def can_edit_agreement?
    @agreement.pendiente? || current_user.juridico?
  end

  # Regla 1 y 2
  def can_manage_technicals?
    @agreement.pendiente? || current_user.juridico?
  end

  # Regla 1, 2 y 3
  def can_manage_documents?
    return true if @agreement.pendiente?
    return true if @agreement.aprobado? && (current_user.creator_of?(@agreement) || current_user.requester_of?(@agreement))
    current_user.juridico?
  end

  def set_users_cyt_actives
    # concentrar y disminuis la recarga de Usuarios
    @users_cyt_actives = Rails.cache.fetch('users_cyt_actives', expires_in: 1.day) do
      User.cyt_actives
    end
  end

end

app/helpers/agreements_helper.rb
module AgreementsHelper

  def cliente_type_label(cliente_type)
    case cliente_type
    when 'persona_moral'
      'Persona moral'
    when 'persona_fisica'
      'Persona física'
    else
      'Tipo desconocido'
    end
  end

end

app/views/agreements/_documents.html.haml
%h4.text-xl.mb-4.text-gray-700 Documentos

%ul.list-disc.pl-5.space-y-2
  - if agreement.documents.any?
    %table.table.w-full
      %thead
        %tr
          %th.text-left Tipo de Documento
          %th.text-left Nombre del Archivo
          %th.text-left Notas
          %th.text-left
      %tbody

        - agreement.documents.where.not(id: nil).each do |doc|
          - if doc.file.attached?
            %tr
              %td.py-0= doc.document_type_name
              %td.py-0= doc.file_name
              %td.py-0= doc.notes.present? ? doc.notes : ""
              %td.py-0
                = link_to rails_blob_path(doc.file, disposition: "inline"), target: "_blank", class: "text-blue-500 hover:text-blue-700 p-1" do
                  %div.tooltip.tooltip-warning.absolute.tooltip-left{ style: "","data-tip" => "Ver documento", }
                    %i.fas.fa-external-link-alt

                - if @can_manage_documents
                  = form_with url: document_path(doc), method: :delete,  confirm: "¿Estás seguro de que deseas eliminar este documento?", data: {turbo: false}, class: "inline" do
                    = button_tag type: :submit, class: "text-red-500 hover:underline ml-4 tooltip tooltip-warning tooltip-left", "data-tip" => "Eliminar documento" do
                      %i.fas.fa-trash

                  -#= form_with url: document_path(doc), method: :delete, class: "inline-block", data: { turbo: false } do
                    %button{ type: "button", class: "text-red-500 hover:text-red-700 p-1", "data-modal-target": "deleteDocumentModal#{doc.id}", title: "Eliminar" }
                      %i.fas.fa-trash

                    / Modal
                    %div.modal{ id: "deleteDocumentModal#{doc.id}" }
                      %div.modal-box
                        %h3.font-bold.text-lg
                          ¿Estás seguro de que deseas eliminar este documento?
                        %p.py-4
                          Este cambio no se puede deshacer.
                        %div.modal-action
                          %button.btn.btn-primary{ type: "submit", title: "Confirmar" }
                            %i.fas.fa-check
                        %button.btn.btn-ghost{ type: "button", "data-modal-close": "deleteDocumentModal#{doc.id}", title: "Cancelar" }
                          %i.fas.fa-times

          - else
            %tr
              %td.py-0= doc.document_type_name
              %td.py-0.text-gray-500 Sin archivo adjunto
              %td.py-0.text-gray-500 Sin notas
              %td.py-0.text-gray-500 Sin acciones

        - if @can_manage_documents
          %tr#document-form
            = form_with model: @document, url: upload_document_agreement_path(@agreement), local: true, class: "space-y-6", multipart: true, data: { turbo: false } do |f|
              %td.py-0
                = f.select :document_type_id, Document::DOCUMENT_TYPES.map { |id, name| [name, id] }, {}, class: "select select-bordered h-full text-sm px-1 py-1"

              %td.py-1
                %div#document_dropzone.border-2.border-dashed.border-gray-300.rounded-lg.p-2.flex.flex-col.items-center.justify-center
                  %p.text-gray-500.text-sm.text-center.mb-2
                    = "Arrastrar y soltar el archivo aquí. Debe ser PDF, JEPG, JPG o PNG."
                  = f.file_field :file, class: "hidden", id: "document_input"
                  -#%button.btn.btn-outline.btn-sm.mt-2{ type: "button", onclick: "document.getElementById('file_input').click()" }
                    Seleccionar Archivo

              %td.py-0
                = f.text_area :notes, class: "textarea textarea-bordered w-full", placeholder: "Notas adicionales sobre el documento"

              %td.py-0
                %button.btn.btn-success.btn-xs.tooltip.tooltip-warning.tooltip-left{ type: "submit", "data-tip" =>  "Agregar documento",
                    disabled: true, id: "add_document_button" }
                  %i.fas.fa-plus

        / Mensajes del flash
        - if flash[:alert_document]
          %tr
            %td{colspan: "4"}
              #alert-document.relative.alert.alert-error.shadow-lg.mt-1.mb-8
                .flex.items-center
                  %i.fa.fa-times-circle.text-red-500.text-xl
                  %span.ml-2= flash[:alert_document]
                %button.absolute.top-1.right-1.btn.btn-circle.btn-ghost.w-6.h-6.flex.items-center.justify-center{"aria-label" => "Cerrar", onclick: "this.parentElement.remove()"}
                  %i.fa.fa-times.text-sm

app/views/agreements/_form.html.haml
-#%div.p-10.bg-blue-500.text-white.text-center
  .h1
    ="TailwindCSS está funcionando 🎉"

-#%style
  @import "daisyui";

-#%div.p-10.flex.flex-col.items-center.space-y-4
  %button.btn.btn-primary DaisyUI funciona 🎉
  %button.btn.btn-secondary Botón secundario
  %button.btn.btn-accent Botón de ac

= form_with model: @agreement, local: true, class: "space-y-6", data: { turbo: false } do |f|
  %div.form-control
    = f.label :title, "Título", class: "label"
    = f.text_field :title, class: "input input-bordered w-full", maxlength: 200, placeholder: "Título del Convenio"

  %div.flex.space-x-4
    %div.form-control{class: "w-1/2"}
      = f.label :agreement_type_id, "Tipo de Convenio", class: "label"
      = f.collection_select :agreement_type_id, AgreementType.all, :id, :name,
                            { prompt: "Seleccione tipo de convenio" },
                            { class: "select select-bordered w-full" }

    %div.flex-1.form-control
      = f.label :requester_id, "Solicitante", class: "label"
      = f.collection_select :requester_id, @users_cyt_actives, :id, :nombre,
                            { prompt: "Seleccione solicitante" },
                            { class: "select select-bordered w-full" }

  %div.form-control
    = f.label :client_name, "Nombre del Cliente", class: "label"
    = f.text_field :client_name, class: "input input-bordered w-full", maxlength: 200

  %div.form-control
    = f.label :client_address, "Dirección del Cliente", class: "label"
    = f.text_field :client_address, class: "input input-bordered w-full", maxlength: 200

  %div.form-control
    %label.label
      %span.label-text Tipo de Cliente
    %div.flex.space-x-4
      %label.flex.items-center.space-x-2
        = f.radio_button :client_type, 'persona_moral', class: "radio"
        %span Persona moral

      %label.flex.items-center.space-x-2
        = f.radio_button :client_type, 'persona_fisica', class: "radio"
        %span Persona física

  %div.form-control
    = f.label :witness_name, "Nombre del Testigo", class: "label"
    = f.text_field :witness_name, class: "input input-bordered w-full", maxlength: 200

  %div.form-control
    = f.label :witness_position, "Cargo del Testigo", class: "label"
    = f.text_field :witness_position, class: "input input-bordered w-full", maxlength: 200

  %div.form-control
    = f.label :objective, "Objetivo", class: "label"
    = f.text_area :objective, class: "textarea textarea-bordered w-full"

  %div.form-control
    = f.label :obligations, "Obligaciones", class: "label"
    = f.text_area :obligations, class: "textarea textarea-bordered w-full"

  %div.form-control
    = f.label :benefits, "Beneficios", class: "label"
    = f.text_area :benefits, class: "textarea textarea-bordered w-full"

  %div.flex.space-x-4
    %div.form-control{class: 'w-1/3'}
      = f.label :signature_date, "Fecha de Firma", class: "label"
      = f.date_field :signature_date, class: "input input-bordered w-full"

    %div.form-control{class: 'w-1/3'}
      = f.label :start_date, "Fecha de Inicio", class: "label"
      = f.date_field :start_date, class: "input input-bordered w-full"

    %div.form-control{class: 'w-1/3'}
      = f.label :end_date, "Fecha de Término", class: "label"
      = f.date_field :end_date, class: "input input-bordered w-full"

  %div.flex.justify-end
    %div.form-control{ style: "max-width: 200px;" }
      = f.label :amount, "Monto", class: "label text-right"
      = f.number_field :amount, step: "0.01", min: "0", class: "input input-bordered text-right w-full", placeholder: "0.00"

  %div.flex.space-x-4
    %div.form-control.block{ style: "margin-right: 2rem !important;" }
      = f.check_box :signed_by_client, class: "checkbox"
      = f.label :signed_by_client, "Firmado por Cliente", class: "ml-2"

    %div.form-control.block{ style: "margin-right: 2rem !important;" }
      = f.check_box :signed_by_requester, class: "checkbox"
      = f.label :signed_by_requester, "Firmado por Solicitante", class: "ml-2"

    %div.form-control.block
      = f.check_box :signed_by_director, class: "checkbox"
      = f.label :signed_by_director, "Firmado por Director", class: "ml-2"

  %div.form-control
    = f.label :notes, "Notas", class: "label"
    = f.text_area :notes, class: "textarea textarea-bordered w-full"

  / Mensajes flash debajo del formulario
  - if flash[:alert]
    .my-4
      #alert-agreement.alert.alert-error.shadow-lg
        %ul.list-disc.pl-6
          - flash[:alert].each do |msg|
            %li= msg

  %div.flex.justify-end.space-x-2.mt-4
    %button#btn-save-agreement.btn.btn-circle.btn-primary{type: "submit",
      title: "Guardar cambios",
      "aria-label" => "Guardar cambios"
    }
      %i.fas.fa-check.text-xl

    = link_to @agreement,
      class: "btn btn-circle btn-outline",
      title: "Cancelar cambios",
      "aria-label" => "Cancelar cambios" do
      %i.fas.fa-times.text-xl

:javascript
  document.addEventListener("DOMContentLoaded", () => {
    const errorsDiv = document.getElementById("alert-agreement");
    if (errorsDiv) {
      errorsDiv.scrollIntoView({ behavior: "smooth" });
    }
  });

app/views/agreements/_members.html.haml
%h4.text-xl.mb-4.text-gray-700 Participantes

%table.table.w-full
  %thead
    %tr
      %th Nombre
      %th Rol
      %th Nota
      %th
  %tbody{id: "members_tbody"}
    %tr
      %td{ class: "px-1 py-1" }
        = agreement.creator.nombre
      %td{ class: "px-1 py-1" }
        Propietario
      %td{ class: "text-xs px-1 py-1" }

    - agreement.members.where.not(id: nil).each do |member|
      %tr{id: "member_#{member.id}"}
        %td.p-0= member.user.nombre
        %td.p-0= member.profile_human
        %td.p-0= member.notes
        %td.p-0
          - if @can_manage_technicals
            = form_with url: agreement_member_path(agreement, member), method: :delete, class: "inline-block", data: { turbo: false } do
              %button.tooltip.tooltip-warning.tooltip-left{ type: "button", class: "text-red-500 hover:text-red-700 p-1",
                    "data-modal-target": "deleteModal#{member.id}", "data-tip" => "Eliminar participante" }
                %i.fas.fa-trash

              / Modal
              %div.modal{ id: "deleteModal#{member.id}" }
                %div.modal-box
                  %h3.font-bold.text-lg
                    ¿Estás seguro de que deseas eliminar este participante?
                  %p.py-4
                    Este cambio no se puede deshacer.
                  %div.modal-action.flex.justify-end.space-x-2
                    %button.btn.btn-circle.btn-primary{ type: "submit", title: "Confirmar" }
                      %i.fas.fa-check.text-lg
                    %button.btn.btn-circle.btn-ghost{ type: "button", "data-modal-close": "deleteModal#{member.id}", title: "Cancelar" }
                      %i.fas.fa-times.text-lg

    - if @can_manage_technicals
      %tr#member-form
        - disable_requester = agreement.members.where(profile: "requester").exists?
        - new_member ||= agreement.members.new
        = form_with model: [agreement, new_member], url: agreement_members_path(agreement),  local: true,  method: :post, multipart: true, data: { turbo: false } do |f_tr|
          %td{ class: "text-xs px-1 py-1" }
            = f_tr.collection_select :user_id, @users_cyt_actives, :id, :nombre,
                                    {prompt: "Seleccione participante"},
                                    {class: "select select-bordered text-ms h-full text-sm px-1 py-1", id: :select_member_id,
                                      onchange: "toggleAddMemberButton()", disabled: disable_requester && new_member.profile == "requester"}

          %td{ class: "text-xs px-1 py-1" }
            = f_tr.collection_select :profile, Member.profiles.map { |key, _| [Member.new(profile: key).profile_human, key] },
                           :last, :first,
                           {prompt: "Seleccione perfil"},
                           {class: "select select-bordered text-ms w-40 h-full text-sm px-1 py-1 ", id: :select_profile_id , onchange: "toggleAddMemberButton()"}

          %td.px-1.py-0
            = f_tr.text_field :notes, class: "textarea textarea-bordered w-full", placeholder: "Notas adicionales sobre el participante",
              maxlength: "200"
          %td.py-1.py-0
            %button.btn.btn-success.btn-xs.tooltip.tooltip-warning.tooltip-left{ type: "submit", "data-tip" => "Agregar participante" ,
              disabled: true, id: "add_member_button"}
              %i.fas.fa-plus

    / Mensajes del flash
    - if flash[:alert_member]
      %tr
        %td{colspan: "3"}
          #alert-member.relative.alert.alert-error.shadow-lg.mt-1.mb-2
            .flex.items-center
              %i.fa.fa-times-circle.text-red-500.text-xl
              %span.ml-2= flash[:alert_member]
            %button.absolute.top-1.right-1.btn.btn-circle.btn-ghost.w-6.h-6.flex.items-center.justify-center{"aria-label" => "Cerrar", onclick: "this.parentElement.remove()"}
              %i.fa.fa-times.text-sm

:javascript

  function toggleAddMemberButton() {
    const addButton = document.getElementById("add_member_button");
    const selectProfile = document.getElementById("select_profile_id");
    const selectMember = document.getElementById("select_member_id");
    if (selectProfile && selectMember && addButton) {
      addButton.disabled = selectProfile.value === "" || selectMember.value === "" ;
    }
  }

app/views/agreements/edit.html.haml
%div.container.mx-auto.p-6
  %h1.text-2xl.font-bold.mb-4.text-gray-700
    = @agreement.new_record? ? "Nuevo Convenio" : "Editar Convenio"

  = render "form"

app/views/agreements/index.html.haml
/ %h2.text-2xl.text-gray-700.m-0 Convenios

/ Campo de entrada de búsqueda
%div.flex.items-center.space-x-4.p-2
  %div.relative.flex-grow
    %input#search-box.form-input.input-bordered.w-full.rounded-lg.pl-2.pr-10{ type: "text",
      placeholder: "Buscar por código, título, cliente o status ...",
      "data-controller" => "filter",
      "data-action" => "input->filter#search",
      "data-turbo-permanent" => true,
      autofocus: true
    }
    %i.fas.fa-search{ class: "absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400" }
  = link_to new_agreement_path, class: "btn btn-sm btn-circle btn-outline flex items-center justify-center" do
    %span.tooltip.tooltip-warning.tooltip-left{"data-tip" => "Agregar nuevo convenio", }
      %i.fas.fa-plus.text-xl

/ Tabla de Convenios h-full
-#%div.overflow-x-auto.overflow-y-auto.max-h-96
%div.overflow-x-auto.overflow-y-auto.w-full{"style" => "height: calc(100vh - 200px);"}
  %table.table.table-of-agreements.w-full.text-xs
    %thead.sticky.top-0.bg-base-200.z-10
      %tr
        %th Código
        %th Título
        %th Tipo
        %th Solicitante
        %th Cliente
        %th Status
    %tbody{"data-controller" => "filter"}
      - @agreements.each do |agreement|
        / data: {turbo: false}, "data-turbo"=>"false",
        / los nombres de los atributos sale del scope Agreement.for_table
        %tr.cursor-pointer.hover:bg-gray-100{
          "data-controller" => "navigate", "data-action" => "click->navigate#toShow", "data-navigate-url" => agreement_path(agreement),
          "data-title" => agreement.title, "data-client" => agreement.client_name,
          "data-status" => agreement.status_human, "data-code" => agreement.formatted_code,
          "data-requester" => agreement.requester.nombre,
          "data-filter-target" => "agreementRow"}
          %td{class: "w-[120px] text-right"}
            %span.badge.badge-soft.badge-neutral.text-xs.w-full.p-0{"data-code" => agreement.formatted_code}
              = agreement.formatted_code
          %td{"data-title" => agreement.title}= agreement.title
          %td{class: "min-w-[200px]"}
            -#%span.badge.badge-ghost.badge-xs.custom-badge-code
              = agreement.type_acronym
            %span
              -#{"data-type_name" => agreement.type_name}
              - if agreement.agreement_type
                = agreement.agreement_type.name
              - else
                = 'No hay'
            %td{class: "min-w-[130px]", "data-requester" => agreement.requester.nombre}
              = @employees_on_agreements[agreement.requester_id.to_s.rjust(5, '0')]&.short_name
          %td{"data-client" => agreement.client_name}= agreement.client_name
          %td
            - status_info = Agreement.status_info(agreement.status)
            %span.flex.items-center.space-x-2{ class: status_info[:color] }
              %i.pr-1{ class: status_info[:icon] }
              %span{"data-status" => agreement.status_human}
                = agreement.status_human || "N/A"